/**
 * Step 22: Cybersecurity Best Practices (OWASP & SSL/TLS)
 * Architecture: Defense in Depth (DiD)
 * Objective: Hardening the Node.js API against the OWASP Top 10 Vulnerabilities.
 */

const express = require('express');
const https = require('https');
const fs = require('fs');
const helmet = require('helmet'); // Security HTTP Headers
const rateLimit = require('express-rate-limit'); // DDoS & Brute Force Protection

const app = express();

// --- 🛡️ SECURITY LAYER 1: HTTP Header Hardening (OWASP Security Misconfiguration) ---
// Helmet automatically hides the 'X-Powered-By' header and adds protections against 
// Clickjacking (X-Frame-Options) and Cross-Site Scripting (X-XSS-Protection).
app.use(helmet());

// --- 🛡️ SECURITY LAYER 2: Request Rate Limiting (DDoS Mitigation) ---
// Prevents an attacker from overwhelming our API Gateway with millions of requests.
const globalLimiter = rateLimit({
    windowMs: 15 * 60 * 1000, // 15 minutes window
    max: 100, // Limit each IP to 100 requests per window
    message: { error: 'Security Fault: Too many requests from this IP. Traffic temporarily blocked.' }
});
app.use('/api/', globalLimiter);

// --- 🛡️ SECURITY LAYER 3: Input Payload Sanitization ---
// Express JSON parser with strict size limits to prevent Memory Exhaustion attacks.
app.use(express.json({ limit: '10kb' }));

// Simulate Input Validation (Mitigating OWASP Injection Attacks)
const strictSanitizer = (req, res, next) => {
    const payload = JSON.stringify(req.body);
    // Extremely basic Regex to block HTML tags (Preventing Cross-Site Scripting - XSS)
    if (/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi.test(payload)) {
        return res.status(403).json({ error: 'Security Fault: Malicious payload detected and neutralized.' });
    }
    next();
};

app.post('/api/v2/secure-endpoint', strictSanitizer, (req, res) => {
    res.status(200).json({ message: 'Payload inspected and processed securely.' });
});

// --- 🔒 SECURITY LAYER 4: SSL/TLS Transport Layer Security ---
// In an Enterprise setup, data must NEVER travel in plaintext (HTTP). We enforce HTTPS.
const PORT = process.env.PORT || 443; // Standard secure port

/* 
  NOTE: In a real environment, we would load valid cryptographic keys generated by a CA (like Let's Encrypt).
  const sslOptions = {
      key: fs.readFileSync('./certs/private-key.pem'),
      cert: fs.readFileSync('./certs/public-certificate.pem')
  };
  https.createServer(sslOptions, app).listen(PORT, () => {
      console.log(`🔒 Enterprise Secure API Gateway running on HTTPS (Port ${PORT})`);
  });
*/

// Fallback for demonstration execution without real certificates:
app.listen(8080, () => {
    console.log(`🛡️ Enterprise Security Mechanisms (Helmet, Rate Limiting, Sanitization) are active.`);
});
